---
- name: Configure AWS.
  shell: aws configure set {{ item.key }} {{ item.value }} --profile {{ aws_profile }}
  no_log: True
  with_dict:
    aws_access_key_id: "{{ aws_access_key }}"
    aws_secret_access_key: "{{ aws_secret_key }}"
    aws_session_token:  "{{ aws_session_token }}"
    region: "{{ aws_region }}"
    format: "{{ aws_format }}"