---
- name: Install package dependencies.
  package: name={{ item }} state=present
  with_items:
    - python3
    - unzip

- name: Download the awscli bundle.
  get_url: url=https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip dest=/tmp/awscli-exe.zip

- name: Unarchive the installer.
  unarchive: src=/tmp/awscli-exe.zip dest=/tmp remote_src=yes creates=/tmp/aws

- name: Install awscli package.
  shell: 
    cmd: ./aws/install 
    chdir: /tmp
    creates: /usr/local/bin/aws

- name: Configure AWS.
  shell: aws configure set {{ item.key }} {{ item.value }} --profile {{ aws_profile }}
  no_log: True
  with_dict:
    aws_access_key_id: "{{ aws_access_key }}"
    aws_secret_access_key: "{{ aws_secret_key }}"
    region: "{{ aws_region }}"
    format: "{{ aws_format }}"
  changed_when: false