---
- name: Get latest kubectl version
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: version
  
- name: create kubectl versioned directory
  file:
    path: /opt/kubectl-{{ version.content }}
    state: directory

- name: Download the latest kubectl release
  uri:
    url: https://dl.k8s.io/release/{{ version.content }}/bin/linux/amd64/kubectl
    dest: /opt/kubectl-{{ version.content }}
  register: kubectl

- name: Change kubectl file permission
  file:
    path: "/opt/kubectl-{{ version.content }}/kubectl"
    mode: '0755'

- name: create a symlink to kubectl
  file:
    src: "/opt/kubectl-{{ version.content }}/kubectl"
    dest: "/usr/bin/kubectl"
    state: link