---
- name: Download helm package.
  get_url: url=https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 dest=/tmp/get_helm.sh mod=0755

- name: Install helm package.
  shell: 
    cmd: ./get_helm.sh
    chdir: /tmp
    creates: /usr/local/bin/helm