---
- hosts: jenkins-master
  become: true
  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jre
        state: present
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
    - name: Start Jenkins
      service:
        name: jenkins
        state: started
        enabled: yes
    - name: enable jenkins to start on boot
      service:
        name: jenkins
        enabled: yes